"use client";
import { useCallback,useEffect,useMemo,useRef,useState,type FormEvent } from "react";
import { importTindeqArchive } from "@/lib/tindeq-browser";
import { forceToKg } from "@/lib/tindeq-persistence";
import { loadWorkflowHistory,saveWorkflowSession,type StoredWorkflowSession } from "@/lib/tindeq-workflow-persistence";
import { calculateMaximumMeasurement,calculateTargetForce,getTindeqClientNameCandidate,matchAthletesByExactName,normalizeClientName,parseOptionalPain,type ExerciseSide } from "@/lib/tindeq-workflow";
import { useSupabaseSession } from "@/lib/use-supabase-session";
import { RX_SELECT,TEST_SELECT,filterAthletes,keyFor,num,positive,side,today,type Athlete,type Draft,type MaxTest,type Prescription,type Profile } from "./workflow-model";
export function useWorkflowController(){
const auth=useSupabaseSession(),{supabase,session}=auth;
const [email,setEmail]=useState(""),[message,setMessage]=useState("");
const [athletes,setAthletes]=useState<Athlete[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[tests,setTests]=useState<MaxTest[]>([]),[rxs,setRxs]=useState<Prescription[]>([]),[history,setHistory]=useState<StoredWorkflowSession[]>([]);
const [selected,setSelected]=useState(""),selectedRef=useRef(""),[query,setQuery]=useState(""),[loadError,setLoadError]=useState<string|null>(null),[loading,setLoading]=useState(true);
const [client,setClient]=useState({name:"",weight:"",shin:"",note:""}),[profile,setProfile]=useState({weight:"",shin:""});
const [maximum,setMaximum]=useState({date:today(),weight:"",shin:"",left:"",right:"",unit:"kg" as "kg"|"n"|"lb",note:""});
const [rx,setRx]=useState({side:"left" as ExerciseSide,testId:"",pct:"70",note:""}),[drafts,setDrafts]=useState<Draft[]>([]);
const athlete=athletes.find(a=>a.id===selected)??null;
const clientTests=useMemo(()=>tests.filter(t=>t.athlete_id===selected).sort((a,b)=>b.test_date.localeCompare(a.test_date)||(b.created_at??"").localeCompare(a.created_at??"")),[tests,selected]);
const clientRxs=useMemo(()=>rxs.filter(r=>r.athlete_id===selected).sort((a,b)=>b.created_at.localeCompare(a.created_at)),[rxs,selected]);
const visible=filterAthletes(athletes,query);
const latestRx=(athleteId:string,s:ExerciseSide)=>rxs.filter(r=>r.athlete_id===athleteId&&r.exercise_side===s).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0]?.id??"";
const syncSelection=useCallback((athleteId:string,nextProfiles:Profile[],nextTests:MaxTest[])=>{selectedRef.current=athleteId;setSelected(athleteId);const nextProfile=nextProfiles.find(p=>p.athlete_id===athleteId)??null;const weight=nextProfile?.body_weight_kg?.toString()??"",shin=nextProfile?.shin_length_cm?.toString()??"";setProfile({weight,shin});setMaximum(m=>({...m,weight,shin}));const nextTest=nextTests.filter(t=>t.athlete_id===athleteId).sort((a,b)=>b.test_date.localeCompare(a.test_date)||(b.created_at??"").localeCompare(a.created_at??""))[0];setRx(r=>({...r,testId:nextTest?.id??""}))},[]);
const selectAthlete=useCallback((athleteId:string)=>{setHistory([]);syncSelection(athleteId,profiles,tests)},[profiles,tests,syncSelection]);
const load=useCallback(async(preferredSelected?:string)=>{if(!supabase||!session)return;const [a,p,t,r]=await Promise.all([supabase.from("athletes").select("id,display_name,name_key,note").is("deleted_at",null).order("display_name"),supabase.from("athlete_profiles").select("id,athlete_id,body_weight_kg,shin_length_cm").is("deleted_at",null),supabase.from("knee_extension_tests").select(TEST_SELECT).is("deleted_at",null).order("test_date",{ascending:false}),supabase.from("tindeq_prescriptions").select(RX_SELECT).is("deleted_at",null).order("created_at",{ascending:false})]);const e=[a.error,p.error,t.error,r.error].find(Boolean);if(e){setLoadError(e.code==="42P01"||e.message.includes("tindeq_prescriptions")?"Databázová migrace pro klientské Tindeq workflow zatím není aplikována.":e.message);setLoading(false);return}const next=(a.data??[]) as Athlete[],nextProfiles=(p.data??[]) as Profile[],nextTests=(t.data??[]) as MaxTest[];setAthletes(next);setProfiles(nextProfiles);setTests(nextTests);setRxs((r.data??[]) as Prescription[]);const requested=preferredSelected??selectedRef.current,nextSelected=next.some(x=>x.id===requested)?requested:next[0]?.id??"";if(nextSelected!==selectedRef.current)setHistory([]);syncSelection(nextSelected,nextProfiles,nextTests);setLoadError(null);setLoading(false)},[supabase,session,syncSelection]);
useEffect(()=>{let cancelled=false;queueMicrotask(()=>{if(!cancelled)void load()});return()=>{cancelled=true}},[load]);
const loadHistory=useCallback(async(athleteId:string)=>{if(!supabase||!session||!athleteId)return;try{setHistory(await loadWorkflowHistory(supabase,athleteId))}catch(e){setMessage(e instanceof Error?e.message:"Historii nelze načíst.")}},[supabase,session]);
useEffect(()=>{if(!selected)return;let cancelled=false;queueMicrotask(()=>{if(!cancelled)void loadHistory(selected)});return()=>{cancelled=true}},[loadHistory,selected]);
async function login(e:FormEvent){e.preventDefault();if(!supabase)return;const r=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,emailRedirectTo:new URL("/tindeq/workflow",window.location.origin).toString()}});setMessage(r.error?r.error.message:"Přihlašovací odkaz byl odeslán.")}
async function createClient(e:FormEvent){e.preventDefault();if(!supabase)return;let id:string|null=null;try{const name=client.name.trim().replace(/\s+/g," ");if(!name)throw new Error("Jméno je povinné.");if(athletes.some(a=>normalizeClientName(a.display_name)===normalizeClientName(name)))throw new Error("Klient se stejným jménem už existuje.");const weight=positive(client.weight,"Hmotnost"),shin=positive(client.shin,"Délka bérce");const a=await supabase.from("athletes").insert({display_name:name,name_key:keyFor(name),note:client.note.trim()||null}).select("id").single();if(a.error||!a.data)throw new Error(a.error?.message??"Klienta nelze vytvořit.");id=a.data.id;const p=await supabase.from("athlete_profiles").insert({athlete_id:id,body_weight_kg:weight,shin_length_cm:shin,profile_date:today()});if(p.error)throw new Error(p.error.message);setClient({name:"",weight:"",shin:"",note:""});setMessage(`Klient ${name} byl vytvořen.`);await load(id??"")}catch(err){if(id)await supabase.from("athletes").update({deleted_at:new Date().toISOString(),delete_reason:"rollback_failed_profile_creation",deleted_context:"tindeq_client_workflow"}).eq("id",id);setMessage(err instanceof Error?err.message:"Klienta nelze vytvořit.")}}
async function saveProfile(e:FormEvent){e.preventDefault();if(!supabase||!athlete)return;try{const r=await supabase.from("athlete_profiles").upsert({athlete_id:athlete.id,body_weight_kg:positive(profile.weight,"Hmotnost"),shin_length_cm:positive(profile.shin,"Délka bérce"),profile_date:today(),updated_at:new Date().toISOString()},{onConflict:"athlete_id"});if(r.error)throw new Error(r.error.message);setMessage("Antropometrie byla uložena.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Profil nelze uložit.")}}
async function saveMaximum(e:FormEvent){e.preventDefault();if(!supabase||!athlete)return;try{const weight=positive(maximum.weight,"Hmotnost"),shin=positive(maximum.shin,"Délka bérce"),srcL=positive(maximum.left,"Levé maximum"),srcR=positive(maximum.right,"Pravé maximum"),left=forceToKg(srcL,maximum.unit),right=forceToKg(srcR,maximum.unit);if(left==null||right==null)throw new Error("Jednotku nelze převést.");const c=calculateMaximumMeasurement({bodyWeightKg:weight,shinLengthCm:shin,leftForceKg:left,rightForceKg:right});const r=await supabase.from("knee_extension_tests").insert({athlete_id:athlete.id,test_date:maximum.date,left_force_kg:left,right_force_kg:right,left_moment_nm:c.leftMomentNm,right_moment_nm:c.rightMomentNm,left_nm_per_kg:c.leftNmPerKg,right_nm_per_kg:c.rightNmPerKg,asymmetry_pct:c.asymmetryPct,weaker_side:c.weakerSide,body_weight_kg:weight,shin_length_cm:shin,source_force_unit:maximum.unit,source_left_force:srcL,source_right_force:srcR,note:maximum.note.trim()||null,source:"manual"});if(r.error)throw new Error(r.error.message);setMaximum(m=>({...m,left:"",right:"",note:""}));setMessage("Maximum bylo uloženo jako nová historická reference.");await load()}catch(err){setMessage(err instanceof Error?err.message:"Maximum nelze uložit.")}}
async function saveRx(e:FormEvent){e.preventDefault();if(!supabase||!athlete)return;try{const t=clientTests.find(x=>x.id===rx.testId);if(!t)throw new Error("Vyber referenční maximum.");const reference=rx.side==="left"?t.left_force_kg:t.right_force_kg,pct=positive(rx.pct,"Procento"),target=calculateTargetForce(reference,pct);const r=await supabase.from("tindeq_prescriptions").insert({athlete_id:athlete.id,reference_test_id:t.id,reference_test_date:t.test_date,exercise_side:rx.side,reference_force_kg:reference,prescribed_pct:pct,target_force_kg:target,force_unit:"kg",note:rx.note.trim()||null});if(r.error)throw new Error(r.error.message);setMessage(`Předpis uložen: ${side(rx.side)} ${num(target,1," kg")}.`);await load()}catch(err){setMessage(err instanceof Error?err.message:"Předpis nelze uložit.")}}
async function importFile(file:File|null){if(!file)return;try{const result=await importTindeqArchive(file);setDrafts(result.sessions.map((s,i)=>{const candidate=getTindeqClientNameCandidate(s),match=matchAthletesByExactName(candidate,athletes),athleteId=match.kind==="exact"?match.matches[0].id:"",exerciseSide:ExerciseSide="left";return{key:`${s.id}-${i}`,session:s,candidate,match,athleteId,side:exerciseSide,prescriptionId:athleteId?latestRx(athleteId,exerciseSide):"",pain:["","",""] as [string,string,string],confirmed:false,status:"ready",message:null}}));setMessage(`Načteno ${result.sessions.length} výsledků${result.errors.length?`, chybné vnitřní soubory: ${result.errors.length}`:""}.`)}catch(err){setDrafts([]);setMessage(err instanceof Error?err.message:"Soubor nelze analyzovat.")}}
const patch=(key:string,p:Partial<Draft>)=>setDrafts(d=>d.map(x=>x.key===key?{...x,...p}:x));
async function saveImport(d:Draft){if(!supabase)return;const a=athletes.find(x=>x.id===d.athleteId);if(!a)return patch(d.key,{status:"error",message:"Vyber klienta."});if(!d.confirmed)return patch(d.key,{status:"error",message:"Potvrď přiřazení klienta."});const r=rxs.find(x=>x.id===d.prescriptionId)??null;if(r&&(r.athlete_id!==a.id||r.exercise_side!==d.side))return patch(d.key,{status:"error",message:"Předpis nepatří klientovi a straně."});patch(d.key,{status:"saving",message:"Ukládám…"});const result=await saveWorkflowSession(supabase,d.session,{athleteId:a.id,side:d.side,prescription:r?{id:r.id,referenceTestId:r.reference_test_id,referenceTestDate:r.reference_test_date,referenceForceKg:Number(r.reference_force_kg),prescribedPct:Number(r.prescribed_pct),targetForceKg:Number(r.target_force_kg)}:null,sourceClientName:d.candidate,matchMethod:d.match.kind==="exact"&&normalizeClientName(d.candidate??"")===normalizeClientName(a.display_name)?"exact":"manual",pain:{before:parseOptionalPain(d.pain[0]),duringMax:parseOptionalPain(d.pain[1]),after:parseOptionalPain(d.pain[2])}});if(!result.ok){patch(d.key,{status:result.duplicate?"duplicate":"error",message:result.duplicate?`${result.error} Záznam ${result.existing.id}.`:result.error});return}patch(d.key,{status:"saved",message:"Uloženo bez ZIPu a raw časové řady."});selectAthlete(a.id);await loadHistory(a.id)}
return{...auth,email,setEmail,message,athletes,rxs,history,selected,setSelected:selectAthlete,query,setQuery,loadError,loading,client,setClient,profile,setProfile,maximum,setMaximum,rx,setRx,drafts,athlete,clientTests,clientRxs,visible,latestRx,login,createClient,saveProfile,saveMaximum,saveRx,importFile,patch,saveImport};
}
